apiVersion: v1
kind: Service
metadata:
  name: final
spec:
  selector:
      app: final
  ports:
  - port: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: final
  labels:
    app: final
spec:
  selector:
    matchLabels:
      app: final
  replicas: 4
  template:
    metadata:
      labels:
        app: final
    spec:
      containers:
      - name: final
        image: cyrusjetson/ibmproject:new
        ports:
        - containerPort: 5000
        env:
        - name: DISABLE_WEB_APP
          value: "false"
